name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          node-version: '20'

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # or 'zulu', 'adopt', etc.
          java-version: '17'
          cache: gradle

      - name: Build with Gradle
        run: ./gradlew build test
